/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ienaclone;

import ienaclone.gui.Window;

public class App {

    public static void main(String[] args) {
        Window.main(args);
    }
}
